name: Test CLI Tool on macos

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-cli:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify the Python version you need

      - name: Install CLI Tool
        run: |
          python -m pip install --upgrade pip
          pip install dvcartifacts

      - name: Run CLI Tool
        run: |
          dvcartifacts -h